//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace collectCoins.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GeneralCoin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralCoin()
        {
            this.CoinsCollections = new HashSet<CoinsCollection>();
        }
    
        public int GeneralCoinId { get; set; }
        [Required]
        public double Value { get; set; }
        [Required]
        public double Diameter { get; set; }
        [Required]
        public double Weight { get; set; }
        [Required]
        public double Thickness { get; set; }
        public string Shape { get; set; }
        public string Notes { get; set; }
        public string Material { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoinsCollection> CoinsCollections { get; set; }
    }
}
